- name: Create EC2 instance with user data
  hosts: localhost
  gather_facts: false
  vars:
    keypair: Stockholm_RSA
    security_group: MySecurityGroup
    instance_type: t3.micro
    ami: ami-09e1162c87f73958b
    instance_name: EC2-instance-created-using-Ansible
    user_data: |
      #!/bin/bash
      sudo apt-get update
      sudo apt-get install -y default-jre
      wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
      sudo sh -c "echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list"
      sudo apt-get update
      sudo apt-get install -y jenkins
  tasks:
    - name: Launch an instance with user data
      amazon.aws.ec2_instance:
        name: "ec2-instance-created-using-ansible_and_jenkins"
        key_name: "{{ keypair }}"
        security_group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image:
          id : "{{ami}}"
        wait: true
        region: eu-north-1
        count: 1
        user_data: "{{ user_data }}"
      register: ec2
      delegate_to: localhost

    - name: Print public ip ec2 instance
      debug:
         var: ec2_instance.instances[0].public_ip_address
